// const DIST1 = Math.sqrt(3) / 2; // height of triangle
// const DIST2 = DIST1 / 3; // center of triangle to bottom
// const DIST3 = DIST2 * 2; // center of triangle to top

var tiles = [
    {
        'type'      : 'hexagon',
        'rotation'  : 30,
        'xOffset'   : 0,
        'yOffset'   : 0,
    },
    {
        'type'      : 'hexagon',
        'rotation'  : 30,
        'xOffset'   : 0,
        'yOffset'   : DIST1 * -6,
    },
    {
        'type'      : 'hexagon',
        'rotation'  : 30,
        'xOffset'   : 0,
        'yOffset'   : DIST1 * -4,
    },
    {
        'type'      : 'hexagon',
        'rotation'  : 30,
        'xOffset'   : 0,
        'yOffset'   : DIST1 * -2,
    },
    {
        'type'      : 'hexagon',
        'rotation'  : 30,
        'xOffset'   : 0,
        'yOffset'   : DIST1 * 2,
    },
    {
        'type'      : 'hexagon',
        'rotation'  : 30,
        'xOffset'   : 0,
        'yOffset'   : DIST1 * 4,
    },
    {
        'type'      : 'diamond',
        'rotation'  : 0,
        'xOffset'   : 1,
        'yOffset'   : DIST1 * -5,
    },
    {
        'type'      : 'diamond',
        'rotation'  : 0,
        'xOffset'   : -1.5,
        'yOffset'   : DIST1 * -4,
    },
    {
        'type'      : 'diamond',
        'rotation'  : 0,
        'xOffset'   : -1,
        'yOffset'   : DIST1 * -3,
    },
    {
        'type'      : 'diamond',
        'rotation'  : 0,
        'xOffset'   : 1.5,
        'yOffset'   : DIST1 * -2,
    },
    {
        'type'      : 'diamond',
        'rotation'  : 0,
        'xOffset'   : 1,
        'yOffset'   : DIST1 * -1,
    },
    {
        'type'      : 'diamond',
        'rotation'  : 0,
        'xOffset'   : -1.5,
        'yOffset'   : 0,
    },
    {
        'type'      : 'diamond',
        'rotation'  : 0,
        'xOffset'   : -1,
        'yOffset'   : DIST1,
    },
    {
        'type'      : 'diamond',
        'rotation'  : 0,
        'xOffset'   : 1.5,
        'yOffset'   : DIST1 * 2,
    },
    {
        'type'      : 'diamond',
        'rotation'  : 0,
        'xOffset'   : 1,
        'yOffset'   : DIST1 * 3,
    },
    {
        'type'      : 'triangle',
        'rotation'  : 60,
        'xOffset'   : -1,
        'yOffset'   : DIST1 * -5 - DIST2,
    },
    {
        'type'      : 'triangle',
        'rotation'  : 0,
        'xOffset'   : -1,
        'yOffset'   : DIST1 * -4 - DIST3,
    },
    {
        'type'      : 'triangle',
        'rotation'  : 60,
        'xOffset'   : 1,
        'yOffset'   : DIST1 * -3 - DIST2,
    },
    {
        'type'      : 'triangle',
        'rotation'  : 0,
        'xOffset'   : 1,
        'yOffset'   : DIST1 * -2 - DIST3,
    },
    {
        'type'      : 'triangle',
        'rotation'  : 60,
        'xOffset'   : -1,
        'yOffset'   : DIST1 * -1 - DIST2,
    },
    {
        'type'      : 'triangle',
        'rotation'  : 0,
        'xOffset'   : -1,
        'yOffset'   : 0 - DIST3,
    },
    {
        'type'      : 'triangle',
        'rotation'  : 60,
        'xOffset'   : 1,
        'yOffset'   : DIST3,
    },
    {
        'type'      : 'triangle',
        'rotation'  : 0,
        'xOffset'   : 1,
        'yOffset'   : DIST1 + DIST2,
    },
    {
        'type'      : 'triangle',
        'rotation'  : 60,
        'xOffset'   : -1,
        'yOffset'   : DIST1 * 2 + DIST3,
    },
    {
        'type'      : 'triangle',
        'rotation'  : 0,
        'xOffset'   : -1,
        'yOffset'   : DIST1 * 3 + DIST2,
    },
    {
        'type'      : 'triangle',
        'rotation'  : 0,
        'xOffset'   : 0,
        'yOffset'   : DIST1 * 5 + DIST2,
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 135,
        'xOffset'   : POINT1_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(-45))),
        'yOffset'   : POINT1_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(-45))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 105,
        'xOffset'   : POINT1_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(-15))),
        'yOffset'   : POINT1_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(-15))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 75,
        'xOffset'   : POINT1_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(15))),
        'yOffset'   : POINT1_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(15))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 45,
        'xOffset'   : POINT1_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(45))),
        'yOffset'   : POINT1_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(45))),
    },
    {
        'type'      : 'triangle',
        'rotation'  : 60,
        'xOffset'   : POINT1_X + ((1 + DIST3) * Math.cos(toRads(-30))),
        'yOffset'   : POINT1_Y + ((1 + DIST3) * Math.sin(toRads(-30))),
    },
    {
        'type'      : 'triangle',
        'rotation'  : 30,
        'xOffset'   : POINT1_X + ((1 + DIST3) * Math.cos(toRads(0))),
        'yOffset'   : POINT1_Y + ((1 + DIST3) * Math.sin(toRads(0))),
    },
    {
        'type'      : 'triangle',
        'rotation'  : 0,
        'xOffset'   : POINT1_X + ((1 + DIST3) * Math.cos(toRads(30))),
        'yOffset'   : POINT1_Y + ((1 + DIST3) * Math.sin(toRads(30))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 45,
        'xOffset'   : POINT2_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(-135))),
        'yOffset'   : POINT2_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(-135))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 75,
        'xOffset'   : POINT2_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(-165))),
        'yOffset'   : POINT2_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(-165))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 105,
        'xOffset'   : POINT2_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(165))),
        'yOffset'   : POINT2_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(165))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 135,
        'xOffset'   : POINT2_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(135))),
        'yOffset'   : POINT2_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(135))),
    },
    {
        'type'      : 'triangle',
        'rotation'  : 60,
        'xOffset'   : POINT2_X + ((1 + DIST3) * Math.cos(toRads(-150))),
        'yOffset'   : POINT2_Y + ((1 + DIST3) * Math.sin(toRads(-150))),
    },
    {
        'type'      : 'triangle',
        'rotation'  : 90,
        'xOffset'   : POINT2_X + ((1 + DIST3) * Math.cos(toRads(180))),
        'yOffset'   : POINT2_Y + ((1 + DIST3) * Math.sin(toRads(180))),
    },
    {
        'type'      : 'triangle',
        'rotation'  : 0,
        'xOffset'   : POINT2_X + ((1 + DIST3) * Math.cos(toRads(150))),
        'yOffset'   : POINT2_Y + ((1 + DIST3) * Math.sin(toRads(150))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 135,
        'xOffset'   : POINT3_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(-45))),
        'yOffset'   : POINT3_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(-45))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 105,
        'xOffset'   : POINT3_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(-15))),
        'yOffset'   : POINT3_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(-15))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 75,
        'xOffset'   : POINT3_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(15))),
        'yOffset'   : POINT3_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(15))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 45,
        'xOffset'   : POINT3_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(45))),
        'yOffset'   : POINT3_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(45))),
    },
    {
        'type'      : 'triangle',
        'rotation'  : 60,
        'xOffset'   : POINT3_X + ((1 + DIST3) * Math.cos(toRads(-30))),
        'yOffset'   : POINT3_Y + ((1 + DIST3) * Math.sin(toRads(-30))),
    },
    {
        'type'      : 'triangle',
        'rotation'  : 30,
        'xOffset'   : POINT3_X + ((1 + DIST3) * Math.cos(toRads(0))),
        'yOffset'   : POINT3_Y + ((1 + DIST3) * Math.sin(toRads(0))),
    },
    {
        'type'      : 'triangle',
        'rotation'  : 0,
        'xOffset'   : POINT3_X + ((1 + DIST3) * Math.cos(toRads(30))),
        'yOffset'   : POINT3_Y + ((1 + DIST3) * Math.sin(toRads(30))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 45,
        'xOffset'   : POINT4_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(-135))),
        'yOffset'   : POINT4_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(-135))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 75,
        'xOffset'   : POINT4_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(-165))),
        'yOffset'   : POINT4_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(-165))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 105,
        'xOffset'   : POINT4_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(165))),
        'yOffset'   : POINT4_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(165))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 135,
        'xOffset'   : POINT4_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(135))),
        'yOffset'   : POINT4_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(135))),
    },
    {
        'type'      : 'triangle',
        'rotation'  : 60,
        'xOffset'   : POINT4_X + ((1 + DIST3) * Math.cos(toRads(-150))),
        'yOffset'   : POINT4_Y + ((1 + DIST3) * Math.sin(toRads(-150))),
    },
    {
        'type'      : 'triangle',
        'rotation'  : 90,
        'xOffset'   : POINT4_X + ((1 + DIST3) * Math.cos(toRads(180))),
        'yOffset'   : POINT4_Y + ((1 + DIST3) * Math.sin(toRads(180))),
    },
    {
        'type'      : 'triangle',
        'rotation'  : 0,
        'xOffset'   : POINT4_X + ((1 + DIST3) * Math.cos(toRads(150))),
        'yOffset'   : POINT4_Y + ((1 + DIST3) * Math.sin(toRads(150))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 105,
        'xOffset'   : POINT5_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(165))),
        'yOffset'   : POINT5_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(165))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 135,
        'xOffset'   : POINT5_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(135))),
        'yOffset'   : POINT5_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(135))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : -15,
        'xOffset'   : POINT5_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(105))),
        'yOffset'   : POINT5_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(105))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 15,
        'xOffset'   : POINT5_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(75))),
        'yOffset'   : POINT5_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(75))),
    },
    {
        'type'      : 'diamond',
        'rotation'  : -60,
        'xOffset'   : POINT5_X + ((1 + DIST1) * Math.cos(toRads(150))),
        'yOffset'   : POINT5_Y + ((1 + DIST1) * Math.sin(toRads(150))),
    },
    {
        'type'      : 'diamond',
        'rotation'  : -30,
        'xOffset'   : POINT5_X + ((1 + DIST1) * Math.cos(toRads(120))),
        'yOffset'   : POINT5_Y + ((1 + DIST1) * Math.sin(toRads(120))),
    },
    {
        'type'      : 'diamond',
        'rotation'  : 0,
        'xOffset'   : POINT5_X + ((1 + DIST1) * Math.cos(toRads(90))),
        'yOffset'   : POINT5_Y + ((1 + DIST1) * Math.sin(toRads(90))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : -15,
        'xOffset'   : POINT6_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(105))),
        'yOffset'   : POINT6_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(105))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 15,
        'xOffset'   : POINT6_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(75))),
        'yOffset'   : POINT6_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(75))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 45,
        'xOffset'   : POINT6_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(45))),
        'yOffset'   : POINT6_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(45))),
    },
    {
        'type'      : 'diamond2',
        'rotation'  : 75,
        'xOffset'   : POINT6_X + (DIAMOND_2_RAD_1 * Math.cos(toRads(15))),
        'yOffset'   : POINT6_Y + (DIAMOND_2_RAD_1 * Math.sin(toRads(15))),
    },
    {
        'type'      : 'diamond',
        'rotation'  : 0,
        'xOffset'   : POINT6_X + ((1 + DIST1) * Math.cos(toRads(90))),
        'yOffset'   : POINT6_Y + ((1 + DIST1) * Math.sin(toRads(90))),
    },
    {
        'type'      : 'diamond',
        'rotation'  : 30,
        'xOffset'   : POINT6_X + ((1 + DIST1) * Math.cos(toRads(60))),
        'yOffset'   : POINT6_Y + ((1 + DIST1) * Math.sin(toRads(60))),
    },
    {
        'type'      : 'diamond',
        'rotation'  : 60,
        'xOffset'   : POINT6_X + ((1 + DIST1) * Math.cos(toRads(30))),
        'yOffset'   : POINT6_Y + ((1 + DIST1) * Math.sin(toRads(30))),
    },
];